name: Build ISO (KERNELOS)

on:
  workflow_dispatch:
  push:
    branches: [ main, "capy/**" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: build-iso-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    name: Validate repository (fast)
    # Run validation for all events except tag pushes (where we do full build-iso)
    if: ${{ !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic tree validation
        run: |
          echo "Tree snapshot:" && ls -la
          test -f README.md || (echo "Missing README.md" && exit 1)
          echo "Validation OK"

  build-iso:
    name: Build ISO artifact
    # Build ISO on tag pushes (v*), on PRs from capy/*, on pushes to capy/*, or on manual dispatch
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'capy/')) || (github.event_name == 'push' && startsWith(github.ref_name, 'capy/')) }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          pacman -Syy --noconfirm
          pacman -S --needed --noconfirm archiso sbsigntools sbctl shim-signed mokutil mtools xorriso dosfstools squashfs-tools libarchive git openssl

      - name: Use project-provided Secure Boot keys (if any)
        if: ${{ secrets.SB_PRIVATE_KEY != '' && secrets.SB_PUBLIC_CERT != '' }}
        run: |
          mkdir -p keys/secureboot
          echo "${{ secrets.SB_PRIVATE_KEY }}" | base64 -d > keys/secureboot/MOK.key
          echo "${{ secrets.SB_PUBLIC_CERT }}" | base64 -d > keys/secureboot/MOK.crt
          chmod 600 keys/secureboot/MOK.key

      - name: Prepare archiso profile (releng or project profile)
        run: |
          if [ -d profiles/kernelos ]; then
            cp -r profiles/kernelos profile
          else
            cp -r /usr/share/archiso/configs/releng profile
            echo -e "linux-zen\nsbsigntools\nsbctl\nshim-signed\nmokutil" >> profile/packages.x86_64
          fi

      - name: Build ISO
        run: |
          mkarchiso -v -w out -o dist profile

      - name: Sign ISO and inject shim/MOK
        run: |
          ISO=$(ls -1 dist/*.iso | head -n1)
          if [ -f scripts/secureboot/sign-iso.sh ]; then
            bash scripts/secureboot/sign-iso.sh "$ISO" out_signed
          else
            mkdir -p out_signed
            cp "$ISO" out_signed/
            sha256sum out_signed/*.iso > out_signed/SHA256SUMS
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernelos-iso
          path: |
            out_signed/*.iso
            out_signed/SHA256SUMS
            out_signed/KERNELOS-MOK.cer
            out_signed/INSTRUCTIONS-SECURE-BOOT-FR.txt

      - name: Summary
        run: |
          echo "ISO build finished. Artifacts uploaded (if present)."